CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

#背面のNFCパッドをGPIOとして利用する
CONFIG_NFCT_PINS_AS_GPIOS=y

#ロータリエンコーダを利用する
CONFIG_INPUT=n
CONFIG_EC11=n
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n

#マウス操作を使用したいので
CONFIG_ZMK_POINTING=n

CONFIG_ZMK_BATTERY_REPORTING=n

# LED関連のZMK未定義設定は削除し、通常のZMK設定のみを使用する