CONFIG_ZMK_BLE=y
    CONFIG_ZMK_USB=y
    
    // 背面のNFCパッドをGPIOとして利用する
    CONFIG_NFCT_PINS_AS_GPIOS=y
    
    // ロータリエンコーダを利用する
    CONFIG_INPUT=n
    CONFIG_EC11=n
    CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n
    
    // マウス操作を使用したいので
    CONFIG_ZMK_POINTING=n
    
    CONFIG_ZMK_BATTERY_REPORTING=n
    
    // 以下バッテリーや接続、レイヤーの状態でXIAO BLEのLEDを変化させるため
    CONFIG_RGBLED_WIDGET=n
    CONFIG_RGBLED_WIDGET_INTERVAL_MS=250
    CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
    CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
    CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=n
    
    CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=n
    #num_cyan
    CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=6
    #sym_yellow
    CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=3
    #jis_white
    CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=7
    #jisnum_cyan
    CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
    #jissys_yellow
    CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=3
    #macarrow_magenta
    CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=5
    #winarrow_magenta
    CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=5
    #BT_blue
    CONFIG_RGBLED_WIDGET_LAYER_8_COLOR=4